[package]
name = "frg"
description = "Compiled programming language with frogs!"
license = "MIT"
version = "1.0.0"
edition = "2024"

[dependencies]
tree-sitter = "0.26.3"
wasm-bindgen = "0.2.105"

[build-dependencies]
cc = "1.2"

[lib]
crate-type = ["cdylib", "rlib"]
