[package]
name = "frg"
description = "Interpreted programming language with frogs!"
license = "MIT"
version = "0.1.1"
edition = "2024"

[dependencies]
# lets fucking goo

# [lib]
# crate-type = ["cdylib"]
